# Site settings
title: 修己以安人
#email: leo4chin@qq.com
description: > # this means to ignore newlines until "baseurl:"
  本分与平常心 
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://hnrainll.github.io" # the base hostname & protocol for your site
#twitter_username: leo4chin
#github_username:  hnrainll

# Build settings
markdown: kramdown
kramdown:
    input: GFM
#markdown: redcarpet

# syntax highlighting
highlighter: rouge
#highlighter: pygments
