name: build-and-deploy-jekyll-site

on:
  push:
    branches: [ "master" ]

jobs:
  blog:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Ruby  
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: '3.3' # Not needed with a `.ruby-version` or `.tool-versions`
        bundler-cache: true # runs 'bundle install' and caches installed gems automatically

    - name: Build Jekyll Site
      run: bundle exec jekyll build

    - name: Copy generated site to server
      env:
        SSH_PRIVATE_KEY: ${{ secrets.SERVER_SSH_KEY }}
        SERVER_HOST: ${{ secrets.SERVER_HOST }}
        SERVER_USER: ${{ secrets.SERVER_USER }}
        SERVER_PATH: ${{ secrets.SERVER_PATH }}
      run: |
        uname -a
        mkdir -p ~/.ssh
        echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        ls -al ~/.ssh
        rsync -avz --delete _site/ $SERVER_USER@$SERVER_HOST:$SERVER_PATH
