name: Build and Deploy Jekyll Site

on:
  push:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Ruby  
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: '3.3' # Not needed with a `.ruby-version` or `.tool-versions`
        bundler-cache: true # runs 'bundle install' and caches installed gems automatically

    - name: Install dependencies
      run: |
          # gem install bundler
          # bundle install
          uname -a
          ruby -v
